---

# to override default variables set here
# a include_vars: vars/file.yml to the top of main.yml

py:
  virtualenv:
    path: "$HOME/.virtualenv"
    state: "present"
    version: 3.11
  modules:
    - openai==0.27.8
    - numpy==1.24.3
    - huggingface-hub==0.15.1
    - langchain==0.0.219
    # - torch==1.9.0
    # - transformers==4.10.3
